---
title: "class10.Rmd"
author: "Shao-An Chen"
date: "2/6/2020"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Analysis of Human Breast Cancer Cells

First we need to import (i.e. read) our input data

```{r}
wisc.df <- read.csv("data/WisconsinCancer.csv")
head(wisc.df)
```

```{r}
wisc.data <- as.matrix(wisc.df[,3:32])
head(wisc.data)

```

```{r}
nrow(wisc.data)
```

```{r}
table(wisc.df$diagnosis)
```

```{r}
grep("_mean", colnames(wisc.data), value=TRUE)
```

```{r}
length(grep("_mean", colnames(wisc.data)))
```

```{r}
round(apply(wisc.df, 2, sd), 2)
```

```{r}
wisc.pr <- prcomp(wisc.data, scale=TRUE)
summary(wisc.pr)
```

```{r}
biplot(wisc.pr)
```

```{r}
attributes(wisc.pr)
```

```{r}
plot(wisc.pr$x[,1], wisc.pr$x[,2], col=wisc.df$diagnosis)
abline(h=0, col="gray", lty=2)
abline(v=0, col="gray", lty=2)
```

```{r}
pr.var <- wisc.pr$sdev^2
head(pr.var)
```


```{r}
wisc.pr.hclust <- hclust(dist(wisc.pr$x[,1:3]), method="ward.D2")
plot(wisc.pr.hclust)
```

```{r}
grps3 <- cutree(wisc.pr.hclust, k=2)
table(grps3)
```

```{r}
plot(wisc.pr$x[,1], wisc.pr$x[,2], col=grps3)
```

```{r}
table(grps3, wisc.df$diagnosis)
```

```{r}
new <- read.csv("data/new_samples.csv")
new
```

```{r}
npc <- predict(wisc.pr, newdata=new)
npc
```

```{r}
plot(wisc.pr$x[,1:2], col=wisc.df$diagnosis)
points(npc[,1],npc[,2], col="blue", pch=15, cex=3)
text(npc[,1], npc[,2], labels = c(1,2), col="white")
```

